### PR TITLE
Redo analysis

### PR DESCRIPTION
**Pull request by bch29**
This shouldn't be merged yet because it's untested. Making the pull request just to make it easy to see the changes and comment on them.

### CODE REVIEW

**Comment by madgen** [comment]
- Guards are needed for the new analysis (whatever is available for our LTS)

**Comment by bch29** [comment]
@madgen one step ahead of you ;)

**Comment by madgen** [comment]
If it passes CI, then it is good to me. What do you think @dorchard?

**Comment by dorchard** [comment]
This looks good to me.

**Comment by bch29** [comment]
Travis is now passing. Any objections to merging?

**Comment by dorchard** [comment]
Great! Go for it.

**Pull request merged**
