### PR TITLE
Bump Nix flake

### PR DESCRIPTION
**Pull request by raehik**
Update Nix flake. Also bumps some dependency upper bounds. Intended as a first step to upgrading the GHC version CamFort uses (if it remains not too awkward).

### CODE REVIEW

**Comment by raehik** [comment]
Currently halted at an `sbv`/z3 nixpkgs issue.

**Comment by dorchard** [comment]
Is this related to why I'm getting failures elsewhere in the CI/CD pipeline perhaps? https://github.com/camfort/camfort/actions/runs/10848848887/job/30106824846

**Comment by raehik** [comment]
That's more likely due to a packaging issue -- the Nix Haskell setup is very strict, only including files specified in the sdist in the build. But I find `samples/fp-check/intconv.f90` in the Cabal file. Maybe an `hpack` will fix it. I'll take a look.

I wouldn't mind disabling some CI while we troubleshoot and upgrade things, if it's spamming your inbox.

**Comment by raehik** [comment]
Figured it out. I'll clean this up and merge myself when ready. @dorchard the only non-Nix changes are a handful of dependency upper bound bumps and tweaking the singletons bounds (see `package.yaml` changes).

**Comment by dorchard** [comment]
> Figured it out. I'll clean this up and merge myself when ready. @dorchard the only non-Nix changes are a handful of dependency upper bound bumps and tweaking the singletons bounds (see `package.yaml` changes).

Great - thanks!

**Comment by raehik** [comment]
The Nix build is now happy on bleeding edge on nixpkgs-unstable, building on GHC 9.2 (default) and GHC 9.4. (Updated from a 1.5yr old nixpkgs, and probably only building on GHC 9.2.)

**Comment by raehik** [comment]
For clarity, it's very safe to rebase on top of these commits, and if it results in a merge conflict the resolution should be extremely obvious. Ping me if something does break regardless.

**Comment by raehik** [comment]
> Is this related to why I'm getting failures elsewhere in the CI/CD pipeline perhaps? https://github.com/camfort/camfort/actions/runs/10848848887/job/30106824846

The file that fails `samples/fp-check/intconv.f90` I can't find in the source tree for that job run (commit 5453cd1 ). Did it get messed in a Git commit?

Also, I see you tweaked the Stack setup. That's super old, almost guaranteed to no longer work, and in my opinion isn't all that useful anymore (Cabal by itself is fine, and Nix performs a similar/better job of "pinning" for reproducibility). One vote here for deleting the Stack build config.

**Pull request merged**
