### PR TITLE
IO in Analyses

### PR DESCRIPTION
**Pull request by bch29**
Allow analyses to use IO by adding IO to the bottom of the `Analysis` type transformer stack.

I can't run tests locally for some reason as I'm getting linker errors. Hopefully Travis can run the tests for me.

EDIT: Apparently all is good!

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
@bch29 I did consider doing this, but decided against it as I wanted the `Analysis` type to only work without IO, and any IO that needs to be performed is done in `Camfort.Input`/`Camfort.Functionality`.

Why is it that you want `Analysis` to be able to directly access IO?

**Comment by GuiltyDolphin** [comment]
@bch29 @mrd Just mentioned the reason for this is that we have IO in the SBV backend.

As mentioned on Slack, in this case I would rather we use `unsafePerformIO` as this is an edgecase, and in just allowing for this edgecase via `unsafePerformIO`, we prevent other `Analysis` code from accessing IO (which we don't want it to be able to!).

**Comment by bch29** [comment]
There's no point in declaring that 'analyses shouldn't do I/O because we don't know what they might do'. We're the ones writing these analyses. If we need I/O, we should be able to use it. I think it's good enough to make informal rules like 'don't touch the Fortran source files during your analysis'.

The reason why `unsafePerformIO` is particularly unpleasant for SBV is that it results in weird behaviour when SBV throws exceptions. Ideally, if we're using SBV correctly, it won't throw exceptions. However:
- We can't guarantee we're always using it right
- It's not a very stable library, and sometimes throws exceptions because of bugs
- When implementing an analysis, I'm going to do things wrong every now and then, and get an exception from SBV. Then I lose all of my other debugging output, so I can't even see what caused the issue.

**Comment by bch29** [comment]
To be honest, I disagree with the whole `Analysis` abstract monad idea anyway. An analysis is nothing more than a function from a Fortran source file to some output. It could very easily have the type `ProgramUnit (Analysis a) -> b` (where `b` may include `IO`).

If you want to provide shared functionality, provide a library of functions rather than enforcing that all analyses take place within a particular monad. `WriterT` and `StateT` might be useful to the analysis itself, but it can easily layer them in its own computation and run them before it finishes.

**Comment by GuiltyDolphin** [comment]
@bch29 Yes, I agree, `Analysis` has somewhat outgrown its initial bounds, and we will likely want to deal with it sooner rather than later.

Really, we shouldn't need to worry about `ModFiles` (and thus require access to them) in any 'analyses', we should already have normalized the `ProgramFile`s before they are passed to the analysis. Assuming you can ensure that _no_ analyses ever need to access `ModFiles`, then you should be able to remove `Analysis` entirely.

Many analyses also provide debugging information (either through their own mechanisms, via `Analysis`, or using `Debug.Trace` (which we should definitely deal with!), so we'd probably want to maintain a consistent method for providing (user-level) debugging information.

**Comment by bch29** [comment]
Superseded by #109

**Pull request closed without merging**
