### PR TITLE
Hoare Logic Checking

### PR DESCRIPTION
**Pull request by bch29**
I'd like to get this merged before I finish. Do I need to do anything else before that can happen?

### CODE REVIEW

**Comment by dorchard** [comment]
It doesn't really touch much of the existing functionality does it? If not I think we can merge it without having to do much else (assuming all the tests pass).

**Comment by bch29** [comment]
The Travis build says it's failing to download `z3.zip`. Can someone check that out? That shouldn't have anything to do with the Haskell code at all.

**Comment by madgen** [comment]
@bch29 I think it was an accidental error on Travis servers. I rerun the build and it fetched Z3 fine.

Yes, now it complains that there is no verifiable-expressions in the parent directory. I thought you were going to make it a Hackage package. I don't really want to add another dependency depending on the directory structure. Pointing to Git repo would be okay, but Hackage & Stackage is better IMO. In particular it helps with the build time.

**Comment by bch29** [comment]
OK, well I currently have a [pull request](https://github.com/VinylRecords/Vinyl/pull/104) in vinyl that  needs to be merged and pushed to hackage before I can put my library on hackage. Anthony has said he'll merge it, he just wants to give it a little time first.

**Comment by madgen** [comment]
Sure. You'll make it a package as soon as vinyl pull your changes and updates the package on Hackage though right?

I'll merge it when it passes CI.

**Comment by madgen** [comment]
@bch29 So your branch has UnitsSpec which doesn't exist in the master or the repo. I think you accidentally kept it during the merge. Also it seems you have a TranslateSpec which is not listed in the cabal file.

**Comment by bch29** [comment]
> You'll make it a package as soon as vinyl pull your changes and updates the package on Hackage though right?

Yep.

> So your branch has UnitsSpec which doesn't exist in the master or the repo. I think you accidentally kept it during the merge. Also it seems you have a TranslateSpec which is not listed in the cabal file.

Should be fixed now. `TranslateSpec` never actually developed into a proper test suite. I've deleted it for now.

**Comment by madgen** [comment]
Congratulations @bch29 on implementing a badass Hoare logic framework for a beast of a language and doing a great UROP.

**Pull request merged**
